spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      ddl-auto: validate
#    database-platform: 'org.hibernate.dialect.H2Dialect'
  datasource:
#    url: jdbc:h2:mem:mydb
    url: 'jdbc:h2:file:./db'
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#    url: './app.db'
#      url: 'jdbc:h2:file:./db'
#      url: 'jdbc:h2:file:X:/ProgramFiles/JetBrains/IdeaProjects/ZTW_Projekt/db'

  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true
